version: "3.8"

services:

  prism-node:
    image: ghcr.io/input-output-hk/prism-node:${PRISM_NODE_VERSION}
    environment:      
      NODE_LEDGER: ${NODE_LEDGER}
      NODE_PSQL_HOST: ${PGHOST}:${PGPORT:-5432}
      NODE_PSQL_DATABASE: ${NODE_PGDATABASE:-node}
      NODE_PSQL_USERNAME: ${PGUSER}
      NODE_PSQL_PASSWORD: ${PGPASSWORD}
      NODE_NETWORK: ${NETWORK:-mainnet}
      NODE_CARDANO_WALLET_ID: ${WALLET_ID}
      NODE_CARDANO_NETWORK: ${NETWORK:-mainnet}
      NODE_CARDANO_PAYMENT_ADDRESS: ${WALLET_PAYMENT_ADDRESS}
      NODE_CARDANO_WALLET_PASSPHRASE: ${WALLET_PASSPHRASE}
      NODE_CARDANO_WALLET_API_HOST: ${WALLET_HOST}
      NODE_CARDANO_WALLET_API_PORT: ${WALLET_PORT}
      NODE_CARDANO_WALLET_ROUTING_HEADER_NAME: ${WALLET_ROUTING_HEADER}
      NODE_CARDANO_DB_SYNC_HOST: ${PGHOST}:${PGPORT:-5432}
      NODE_CARDANO_DB_SYNC_DATABASE: ${CARDANO_PGDATABASE:-cardano}
      NODE_CARDANO_DB_SYNC_USERNAME: ${PGUSER}
      NODE_CARDANO_DB_SYNC_PASSWORD: ${PGPASSWORD}

  vault-server:
    image: hashicorp/vault:latest
    ports:
      - "127.0.0.1:8200:8200"
    environment:
      VAULT_ADDR: ${VAULT_ADDR:-http://127.0.0.1:8200}
      VAULT_API_ADDR: ${VAULT_ADDR:-http://127.0.0.1:8200}
      VAULT_USE_SEMANTIC_PATH: 'false'
      VAULT_RENEW: ${VAULT_RENEW:-0}
    volumes:
    - ./configs/vault.hcl:/vault/config/config.hcl:ro
    - /opt/vault:/vault/data
    command: server
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  prism-agent:
    image: ghcr.io/input-output-hk/prism-agent:${PRISM_AGENT_VERSION}
    environment:
      POLLUX_DB_HOST: ${PGHOST}
      POLLUX_DB_PORT: ${PGPORT:-5432}
      POLLUX_DB_NAME: ${POLLUX_PGDBDATABASE:-pollux}
      POLLUX_DB_USER: ${PGUSER}
      POLLUX_DB_PASSWORD: ${PGPASSWORD}
      CONNECT_DB_HOST: ${PGHOST}
      CONNECT_DB_PORT: ${PGPORT:-5432}
      CONNECT_DB_NAME: ${CONNECT_PGDBDATABASE:-connect}
      CONNECT_DB_USER: ${PGUSER}
      CONNECT_DB_PASSWORD: ${PGPASSWORD}
      AGENT_DB_HOST: ${PGHOST}
      AGENT_DB_PORT: ${PGPORT:-5432}
      AGENT_DB_NAME: ${AGENT_PGDBDATABASE:-agent}
      AGENT_DB_USER: ${PGUSER}
      AGENT_DB_PASSWORD: ${PGPASSWORD}
      DIDCOMM_SERVICE_URL: http://${AGENT_HOST}:${AGENT_PORT}/didcomm
      REST_SERVICE_URL: http://${AGENT_HOST}:${AGENT_PORT}/prism-agent
      PRISM_NODE_HOST: prism-node
      PRISM_NODE_PORT: 50053
      VAULT_ADDR: ${VAULT_ADDR:-http://vault-server:8200}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_USE_SEMANTIC_PATH: 'false'
      SECRET_STORAGE_BACKEND: vault
      DEFAULT_WALLET_ENABLED: ${WALLET_ENABLED:-true}
      DEFAULT_WALLET_SEED: ${WALLET_SEED}
      DEFAULT_WALLET_WEBHOOK_URL:
      DEFAULT_WALLET_WEBHOOK_API_KEY:
      DEFAULT_WALLET_AUTH_API_KEY:
      GLOBAL_WEBHOOK_URL:
      GLOBAL_WEBHOOK_API_KEY:
      WEBHOOK_PARALLELISM:
      ADMIN_TOKEN:
      API_KEY_SALT: ${AGENT_APIKEY}
      API_KEY_ENABLED: 'true'
      API_KEY_AUTHENTICATE_AS_DEFAULT_USER: 'true'
      API_KEY_AUTO_PROVISIONING:
    depends_on:
      prism-node:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://prism-agent:8085/_system/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.1.0
    environment:
      - 'URLS=[
        { name: "Prism Agent", url: "/docs/prism-agent/api/docs.yaml" }
        ]'

  apisix:
    image: apache/apisix:2.15.0-alpine
    volumes:
      - ./configs/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
      - ./configs/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "${AGENT_PORT}:9080/tcp"
    depends_on:
      - prism-agent
      - swagger-ui